// <auto-generated />
namespace Derby.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Identity20Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Identity20Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201403290150347_Identity-2-0-Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
