// <auto-generated />
namespace Derby.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class RegLock_HeatComplete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegLock_HeatComplete));
        
        string IMigrationMetadata.Id
        {
            get { return "201402251930344_RegLock_HeatComplete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
